version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      - POSTGRES_USER=pybosssa
      - POSTGRES_PASSWORD=pybossa
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server contrib/sentinel.conf --sentinel
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '5000:5000'
    volumes:
      - '.:/pybossa'
#    env_file:
#      - '.env'

volumes:
  redis:
  postgres:
